// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMessageRole } from "./AiMessageRole";

/**
 * 聊天消息。
 */
export type AiMessage = { role: AiMessageRole, content: string, };
