// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作流部署成功后的响应。
 */
export type DeployResponse = { nodeCount: number, edgeCount: number, rootNodes: Array<string>, projectId?: string, workflowId?: string, replacedExisting?: boolean, };
