// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeTypeEntry } from "./NodeTypeEntry";

/**
 * `list_node_types` IPC 命令的响应。
 */
export type ListNodeTypesResponse = { types: Array<NodeTypeEntry>, };
