// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionHealthSnapshot } from "./ConnectionHealthSnapshot";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 已注册连接的内部记录，追踪其借出状态与治理健康信息。
 */
export type ConnectionRecord = { id: string, kind: string, metadata: JsonValue, in_use: boolean, last_borrowed_at?: string, health: ConnectionHealthSnapshot, };
