// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionHealthState } from "./ConnectionHealthState";

/**
 * 连接治理运行时快照。
 */
export type ConnectionHealthSnapshot = { phase: ConnectionHealthState, diagnosis?: string, recommendedAction?: string, lastStateChangedAt?: string, lastConnectedAt?: string, lastHeartbeatAt?: string, lastCheckedAt?: string, lastReleasedAt?: string, lastFailureAt?: string, lastFailureReason?: string, nextRetryAt?: string, circuitOpenUntil?: string, rateLimitedUntil?: string, consecutiveFailures: number, totalFailures: number, timeoutCount: number, rateLimitHits: number, reconnectAttempts: number, lastLatencyMs?: bigint, };
