// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 连接资源的声明式定义（用于全局连接资源库）。
 */
export type ConnectionDefinition = { id: string, type: string, metadata: JsonValue, };
