// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiGenerationParams } from "./AiGenerationParams";
import type { AiMessage } from "./AiMessage";

/**
 * Chat completion 请求。
 */
export type AiCompletionRequest = { 
/**
 * 使用哪个提供商。
 */
providerId: string, 
/**
 * 覆盖默认模型。
 */
model?: string, 
/**
 * 消息列表。
 */
messages: Array<AiMessage>, 
/**
 * 生成参数。
 */
params: AiGenerationParams, 
/**
 * 超时毫秒（None 使用默认 30s）。
 */
timeoutMs?: bigint, };
