// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSecretInput } from "./AiSecretInput";

/**
 * 前端保存配置时的提供商输入。
 */
export type AiProviderUpsert = { id: string, name: string, baseUrl: string, defaultModel: string, extraHeaders: { [key in string]?: string }, enabled: boolean, apiKey: AiSecretInput, };
