// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token 用量统计。
 */
export type AiTokenUsage = { promptTokens: number, completionTokens: number, totalTokens: number, };
